//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modesl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detail
    {
        public string billno { get; set; }
        public int lineid { get; set; }
        public string goodsname { get; set; }
        public decimal goodsnum { get; set; }
        public decimal goodsprice { get; set; }
        public decimal goodsmoneyamt { get; set; }
        public int ispresent { get; set; }
    
        public virtual tb_bill tb_bill { get; set; }
    }
}
